// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: pipe.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StageBuilderService_BuildStageImage_FullMethodName = "/protos.StageBuilderService/BuildStageImage"
)

// StageBuilderServiceClient is the client API for StageBuilderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StageBuilder 서비스: Dockerfile 을 받아 검증 후 빌드 스테이지 이미지 빌드를 수행
type StageBuilderServiceClient interface {
	BuildStageImage(ctx context.Context, in *DockerfileRequest, opts ...grpc.CallOption) (*DockerfileResponse, error)
}

type stageBuilderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStageBuilderServiceClient(cc grpc.ClientConnInterface) StageBuilderServiceClient {
	return &stageBuilderServiceClient{cc}
}

func (c *stageBuilderServiceClient) BuildStageImage(ctx context.Context, in *DockerfileRequest, opts ...grpc.CallOption) (*DockerfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerfileResponse)
	err := c.cc.Invoke(ctx, StageBuilderService_BuildStageImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StageBuilderServiceServer is the server API for StageBuilderService service.
// All implementations must embed UnimplementedStageBuilderServiceServer
// for forward compatibility.
//
// StageBuilder 서비스: Dockerfile 을 받아 검증 후 빌드 스테이지 이미지 빌드를 수행
type StageBuilderServiceServer interface {
	BuildStageImage(context.Context, *DockerfileRequest) (*DockerfileResponse, error)
	mustEmbedUnimplementedStageBuilderServiceServer()
}

// UnimplementedStageBuilderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStageBuilderServiceServer struct{}

func (UnimplementedStageBuilderServiceServer) BuildStageImage(context.Context, *DockerfileRequest) (*DockerfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildStageImage not implemented")
}
func (UnimplementedStageBuilderServiceServer) mustEmbedUnimplementedStageBuilderServiceServer() {}
func (UnimplementedStageBuilderServiceServer) testEmbeddedByValue()                             {}

// UnsafeStageBuilderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StageBuilderServiceServer will
// result in compilation errors.
type UnsafeStageBuilderServiceServer interface {
	mustEmbedUnimplementedStageBuilderServiceServer()
}

func RegisterStageBuilderServiceServer(s grpc.ServiceRegistrar, srv StageBuilderServiceServer) {
	// If the following call pancis, it indicates UnimplementedStageBuilderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StageBuilderService_ServiceDesc, srv)
}

func _StageBuilderService_BuildStageImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StageBuilderServiceServer).BuildStageImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StageBuilderService_BuildStageImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StageBuilderServiceServer).BuildStageImage(ctx, req.(*DockerfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StageBuilderService_ServiceDesc is the grpc.ServiceDesc for StageBuilderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StageBuilderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.StageBuilderService",
	HandlerType: (*StageBuilderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildStageImage",
			Handler:    _StageBuilderService_BuildStageImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pipe.proto",
}
